### ISSUE TITLE
Cannot find template named snmp-defaults at

### ISSUE THREAD

**Issue by glaskoncilla** [ssinyagin/torrus-newfeatures#32]
Hi,

our setup is;

Debian 9.3 fully updated
Perl 5.24.1 (system installation)
Torrus 3.0 - latest git snapshot
all other dependencies are installed using SDBS script

everything worked well for some time but now we have some strange isssue, at the end of discovery we get few warnings ;

[30-Jan-2018 10:15:26 ] 3982.0 Discovery for _**some_ip**_ finished in 12 seconds
Use of uninitialized value $objectName in concatenation (.) or string at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 754.
Use of uninitialized value $objectName in concatenation (.) or string at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 759.
Use of uninitialized value in sprintf at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 765.
Use of uninitialized value $subtreeName in substitution (s///) at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 1014.
Use of uninitialized value $subtreeName in substitution (s///) at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 1015.
Use of uninitialized value $objectName in concatenation (.) or string at /usr/local/torrus/lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm line 1034.
Use of uninitialized value in subroutine entry at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML.pm line 1649.
Use of uninitialized value in subroutine entry at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML.pm line 1649.
Use of uninitialized value in subroutine entry at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML.pm line 1649.
Use of uninitialized value in subroutine entry at /usr/local/lib/x86_64-linux-gnu/perl/5.24.1/XML/LibXML.pm line 1649.
[30-Jan-2018 10:15:39 ] 3982.0 Wrote /usr/local/etc/torrus/xmlconfig/core.xml
/usr/local/bin/torrus compile --tree=main --verbose
[30-Jan-2018 10:15:44 ] Torrus version 3.00
[30-Jan-2018 10:15:44 ] Compiling tree: main
[30-Jan-2018 10:15:51 ] Reading /usr/local/torrus/xmlconfig/defaults.xml
[30-Jan-2018 10:15:51 ] Reading /usr/local/etc/torrus/xmlconfig/site-global.xml
[30-Jan-2018 10:15:51 ] Reading /usr/local/etc/torrus/xmlconfig/core.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/generic/rfc2670.docsis-if.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/generic/rfc2863.if-mib.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/snmp-defs.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/cisco.firewall.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/cisco.generic.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/cisco.ios.cbqos.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/cisco.ios.docsis.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/cisco.ios.xml
[30-Jan-2018 10:15:56 ] Reading /usr/local/torrus/xmlconfig/vendor/netscreen.xml
[30-Jan-2018 10:33:52*] Cannot find template named snmp-defaults at /CORE/**_some_hostname_**/
[30-Jan-2018 10:33:53*] Errors found during XML compilation in the tree named "main"

IP and hostname are not the same host.
Also, I'm not sure is this really an issue, but seems like "Cannot find template named snmp-defaults" always stucks at Cisco 7600 with ES+ hosts.

snmp-defs.xml with snmp-defaults template is present.

Anyone experienced similar issues?

**Comment by ssinyagin** [comment]
hi,
cbQoS errors are most probably caused by some buggy Cisco implementation: on some hardware types, the QoS MIB provides incorrect data. Please try setting "CiscoIOS_cbQoS::classmaps-only" to "yes" in your discovery file. This will reduce the amount of statistics, but will still give quite enough for monitoring.

For the template error, probably something is in a wrong state in the Git repository where Torrus keeps its configuration. If I could have SSH access to the server, that would help in troubleshooting.  Otherwise, you can delete the "gitrepo" folder contents and clean the keys in Redis, and run the compiler from scratch. But of course it would be great to troubleshoot and fix this problem, instead of just deleting the data.

**Comment by glaskoncilla** [comment]
I have suspected the second error was git related and seems like adding --force to compile solves the issue,  compile has come to "preparing a commit" phase at this moment, I guess this would go without errors till the end, will let you know (maybe something worth putting in docs).
 
Unfortunately I can't provide you SSH access because our security team would burn me with fire, but I'm willing to send you any output you would like to see.

Regarding first error, we already have;

<param name="CiscoIOS_cbQoS::classmaps-only" value="yes"/>
<param name="CiscoIOS_cbQoS::suppress-dropnobuf" value="yes"/>
<param name="CiscoIOS_cbQoS::suppress-match-statements" value="yes"/>

If I remember corectly, once upon the time I've had similar issue, it was related with special characters at interface descriptions.
Problem is I don't know how to identify which data source is causing errors, is there any way to pinpoint problematic output?

**Comment by glaskoncilla** [comment]
...we already have;

`
param name="CiscoIOS_cbQoS::classmaps-only" value="yes"
param name="CiscoIOS_cbQoS::suppress-dropnobuf" value="yes"
CiscoIOS_cbQoS::suppress-match-statements" value="yes"
`

bla bla

**Comment by glaskoncilla** [comment]
update, seems like first error triggers second but --force with compilexml solves it every time.
and based on the variable names in the first error, I would say problem is QoS policy map naming.

I don't know how to narrow it down to exact router/interface/policy-map, we have few hundreds potential hosts and number of interfaces/policy-maps is counted in thousands, any ideas?

but I suppose proper solution would be commit to cbqos module which would be tolerant to every potential bullshit someone can configure on the router..

**Comment by ssinyagin** [comment]
I will try to come up with a change, just a bit overloaded with other tasks. But this one is not forgotten :)

**Comment by ssinyagin** [comment]
could you maybe identify the router where this happens and give me a the names that are potentially screwed?

I'm working now on another issue, the QoS is applied to a tunnel interface, and 
```
CISCO-CLASS-BASED-QOS-MIB::cbQosIfType.150704774 = INTEGER: 8
```
which is not a type defined in the MIB.

**Comment by glaskoncilla** [comment]
Is there any switch/option I can add to discovery which would lead to problematic device?
Othervise this would be really hard, it can be any of thousands possible interfaces/policy maps..

**Comment by ssinyagin** [comment]
I pushed commit  30f6277, please check. It should report which mandatory QoS configuration is missing and on which host.

**Comment by ssinyagin** [comment]
Also it automatically removes the incomplete object from configuration, so it should go around the errors.

**Comment by glaskoncilla** [comment]
Ok, will do first thing at Monday

**Comment by glaskoncilla** [comment]
Hi,  I have completely reinstalled Torrus and cbqos plugin with latest Github snapshot but unfortunatelly nothing has changed, we still get bunch of "Use of uninitialized value" during discovery and compile without --force stucks at "Cannot find template named snmp-defaults..".

So it's the same situation as in my first post.

**Comment by ssinyagin** [comment]
strange. Could you contact me in skype or telegram (ssinyagin)? Let's make a screen sharing later today.

**Comment by glaskoncilla** [comment]
I have checked, and seems like patch is correctly installed;

root@torrus:/usr/local/torrus# grep -r "It is recommended to use cbQoS MIB persistency" *
root@torrus:/usr/local/torrus# 
root@torrus:/usr/local/torrus# 
root@torrus:/usr/local/torrus# grep -r "The statistics will be disabled for collection" *
lib/Torrus/DevDiscover/CiscoIOS_cbQoS.pm:                     '. The statistics will be disabled for collection.');

Let make screen sharing later this week, I have another action I must prepare, so I will be available at Thursday or Friday..

**Comment by glaskoncilla** [comment]
solved with 0316bc4
